### ISSUE TITLE
Cargo.toml vgtk version is 0.1.0

### ISSUE THREAD

**Issue by Simhyeon** [bodil/cargo-template-vgtk#1]
Looks like vgtk::Callback doesn't implement std::default::Default trait in 0.1.0. 

Not a big deal since I was able to change cargo.toml by myself but maybe someone might save some time.

![2020-02-23-@01-48-56-scrot](https://user-images.githubusercontent.com/46193352/75096057-c128d200-55de-11ea-8781-d09fa489e5ba.png)

**Comment by bodil** [comment]
Oops, thanks for the spot.
